<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { color: #111; font-size: 12px; margin: 0; }
        .header { border-bottom: 3px solid #facc15; padding-bottom: 14px; margin-bottom: 20px; }
        .header table { width: 100%; }
        .logo { width: 54px; height: 54px; background: #facc15; color: #111; border-radius: 8px; text-align: center; font-weight: bold; font-size: 22px; line-height: 54px; }
        .company { font-size: 18px; font-weight: bold; }
        .muted { color: #777; }
        .title { font-size: 22px; font-weight: bold; margin: 0; }
        .grid { width: 100%; margin: 18px 0; }
        .grid td { vertical-align: top; padding: 4px 0; }
        .label { color: #777; font-size: 10px; text-transform: uppercase; letter-spacing: .5px; }
        .value { font-size: 13px; font-weight: bold; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 8px; }
        table.items th { background: #111; color: #fff; text-align: left; padding: 8px 10px; font-size: 11px; }
        table.items td { padding: 7px 10px; border-bottom: 1px solid #eee; }
        .text-right { text-align: right; }
        .summary { width: 50%; margin-left: 50%; margin-top: 14px; }
        .summary td { padding: 5px 10px; }
        .summary .grand { border-top: 2px solid #111; font-weight: bold; font-size: 14px; }
        .footer { margin-top: 40px; color: #999; font-size: 10px; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <table>
            <tr>
                <td style="width:70px;"><div class="logo">IC</div></td>
                <td>
                    <div class="company">Imprint Customs</div>
                    <div class="muted">Custom Apparel · Established 2013</div>
                </td>
                <td class="text-right">
                    <p class="title">STATEMENT</p>
                    <div class="muted">As of {{ now()->format('M d, Y') }}</div>
                </td>
            </tr>
        </table>
    </div>

    <table class="grid">
        <tr>
            <td style="width:60%;">
                <div class="label">Account</div>
                <div class="value">{{ $customer->name }}</div>
                @if($customer->company)<div class="muted">{{ $customer->company }}</div>@endif
                @if($customer->email)<div class="muted">{{ $customer->email }}</div>@endif
                @if($customer->phone)<div class="muted">{{ $customer->phone }}</div>@endif
            </td>
            <td style="width:40%;" class="text-right">
                <div class="label">Balance due</div>
                <div class="value" style="font-size:20px;">₱{{ number_format($summary['outstanding'], 2) }}</div>
            </td>
        </tr>
    </table>

    <table class="items">
        <thead>
            <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Reference</th>
                <th class="text-right">Charge</th>
                <th class="text-right">Payment</th>
                <th class="text-right">Balance</th>
            </tr>
        </thead>
        <tbody>
            @forelse($ledger as $entry)
                <tr>
                    <td>{{ $entry['date']?->format('M d, Y') }}</td>
                    <td>{{ $entry['type'] }}</td>
                    <td>{{ $entry['reference'] }}</td>
                    <td class="text-right">{{ $entry['charge'] > 0 ? '₱' . number_format($entry['charge'], 2) : '' }}</td>
                    <td class="text-right">{{ $entry['payment'] > 0 ? '₱' . number_format($entry['payment'], 2) : '' }}</td>
                    <td class="text-right">₱{{ number_format($entry['balance'], 2) }}</td>
                </tr>
            @empty
                <tr><td colspan="6" class="muted">No account activity.</td></tr>
            @endforelse
        </tbody>
    </table>

    <table class="summary">
        <tr><td class="muted">Total billed</td><td class="text-right">₱{{ number_format($summary['billed'], 2) }}</td></tr>
        <tr><td class="muted">Total paid</td><td class="text-right">₱{{ number_format($summary['paid'], 2) }}</td></tr>
        <tr class="grand"><td>Balance due</td><td class="text-right">₱{{ number_format($summary['outstanding'], 2) }}</td></tr>
    </table>

    <div class="footer">Generated by Imprint Inventory System · {{ now()->format('M d, Y h:i A') }}</div>
</body>
</html>
